name: social
favicon: null
layout_spectrum: 0.12926
typography_spectrum: 0.99337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#6b6543'
    - '#fd912e'
    - '#d32b04'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
