name: social
favicon: null
layout_spectrum: 0.52729
typography_spectrum: 0.84734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#000000'
    - '#838486'
    - '#c4c9cd'
    - '#282725'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
