name: social
favicon: null
layout_spectrum: 0.55298
typography_spectrum: 0.48125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090601'
    - '#46ab4b'
    - '#463e3c'
    - '#cfcfd1'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
